all:
	g++ -o Flooding_Attack Flooding_Attack.cpp
	g++ -o Launch_Attack Launch_Attack.cpp
	g++ -o Send_Module_Without_Password Send_Module_Without_Password.cpp

clean:
	rm Flooding_Attack Launch_Attack Send_Module_Without_Password
